version: "3.9"

services:
  test:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    command: "bash"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    
    working_dir: "/mnt/model"
    volumes: 
        - .:/mnt/model
    ports: 
        - 7777:8888

